# Based heavily on:
# http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Mimic of development machine miniconda setup
  - conda create --name test-environment python=%PYTHON_VERSION% numpy pyqtgraph pyside
  - activate test-environment

  # On 2016-03-04ish, a build now works with default setuptools -
  # unforutnately, this increase in compatibility manifests as a build
  # error. Something about distribute being the wrong version and/or
  # choco failures
  #- conda remove --name test-environment setuptools
  #- activate test-environment
  # https://github.com/pyinstaller/pyinstaller/issues/1781
  #- "pip install setuptools==19.3"

  - "pip install pyinstaller"
  - "pip install six"
  - "pip install pytest"
  - "pip install pytest-qt"
  - "pip install pytest-capturelog"
  - "pip install pillow"
  - "pip install pyqtgraph"

  - choco install -y InnoSetup
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

# Build is off because it is not applicable to python
build: off

test_script:
  # Run the project tests
     - "python setup.py develop"
     - "py.test tests -s"

after_test:

   - "pyinstaller \
      --distpath=scripts/built-dist \
      --workpath=scripts/work-path \
      --noconfirm \
      --clean \
      --windowed \
      --icon microangio/assets/images/ApplicationIcon.ico \
      --specpath scripts \
      scripts/MicroAngio.py"

      
   - "iscc scripts\\Application_InnoSetup.iss"
   - ps: "ls scripts\\built-dist\\*.exe"
   - ps: "ls scripts\\windows_installer\\*.exe"

   - ps: "7z a MicroAngio.zip scripts\\built-dist"

artifacts:
   - path: MicroAngio.zip
   - path: scripts\windows_installer\*.exe
