# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'microangio/assets/angio_center_configuration.ui'
#
# Created: Thu Apr 21 10:45:01 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(645, 744)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameCenterArea = QtGui.QFrame(Form)
        self.frameCenterArea.setMinimumSize(QtCore.QSize(200, 0))
        self.frameCenterArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameCenterArea.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCenterArea.setObjectName("frameCenterArea")
        self.frame = QtGui.QFrame(self.frameCenterArea)
        self.frame.setGeometry(QtCore.QRect(110, 40, 441, 121))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(30, 20, 171, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton_28 = QtGui.QPushButton(self.frame)
        self.pushButton_28.setGeometry(QtCore.QRect(330, 40, 91, 61))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtGui.QPushButton(self.frame)
        self.pushButton_29.setGeometry(QtCore.QRect(30, 40, 91, 61))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtGui.QPushButton(self.frame)
        self.pushButton_30.setGeometry(QtCore.QRect(230, 40, 91, 61))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtGui.QPushButton(self.frame)
        self.pushButton_31.setGeometry(QtCore.QRect(130, 40, 91, 61))
        self.pushButton_31.setObjectName("pushButton_31")
        self.frame_2 = QtGui.QFrame(self.frameCenterArea)
        self.frame_2.setGeometry(QtCore.QRect(110, 170, 441, 121))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(30, 20, 171, 16))
        self.label_10.setObjectName("label_10")
        self.pushButton_33 = QtGui.QPushButton(self.frame_2)
        self.pushButton_33.setGeometry(QtCore.QRect(30, 40, 91, 61))
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_35 = QtGui.QPushButton(self.frame_2)
        self.pushButton_35.setGeometry(QtCore.QRect(130, 40, 91, 61))
        self.pushButton_35.setObjectName("pushButton_35")
        self.frame_3 = QtGui.QFrame(self.frameCenterArea)
        self.frame_3.setGeometry(QtCore.QRect(110, 300, 441, 121))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_13 = QtGui.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(30, 20, 171, 16))
        self.label_13.setObjectName("label_13")
        self.pushButton_37 = QtGui.QPushButton(self.frame_3)
        self.pushButton_37.setGeometry(QtCore.QRect(30, 40, 91, 61))
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtGui.QPushButton(self.frame_3)
        self.pushButton_38.setGeometry(QtCore.QRect(230, 40, 91, 61))
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtGui.QPushButton(self.frame_3)
        self.pushButton_39.setGeometry(QtCore.QRect(130, 40, 91, 61))
        self.pushButton_39.setObjectName("pushButton_39")
        self.frame_4 = QtGui.QFrame(self.frameCenterArea)
        self.frame_4.setGeometry(QtCore.QRect(170, 430, 381, 219))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtGui.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtGui.QCheckBox(self.frame_4)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 1, 0, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.frame_4)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 3, 0, 1, 1)
        self.checkBox_7 = QtGui.QCheckBox(self.frame_4)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 6, 0, 1, 1)
        self.checkBox_5 = QtGui.QCheckBox(self.frame_4)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 4, 0, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.frame_4)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.checkBox_8 = QtGui.QCheckBox(self.frame_4)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 7, 0, 1, 1)
        self.checkBox_6 = QtGui.QCheckBox(self.frame_4)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 5, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.frame_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frameCenterArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Scan Pattern", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_28.setText(QtGui.QApplication.translate("Form", "Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_29.setText(QtGui.QApplication.translate("Form", "Spiral", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_30.setText(QtGui.QApplication.translate("Form", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_31.setText(QtGui.QApplication.translate("Form", "Rect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Motion Correction", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_33.setText(QtGui.QApplication.translate("Form", "Avg", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_35.setText(QtGui.QApplication.translate("Form", "Subtract", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "Angiography algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_37.setText(QtGui.QApplication.translate("Form", "Speckle", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_38.setText(QtGui.QApplication.translate("Form", "Complex \n"
"Differntial \n"
"Variance", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_39.setText(QtGui.QApplication.translate("Form", "Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Form", "Angio B-scan", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("Form", "Angio Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("Form", "Raw OCT data", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("Form", "Angio Projection", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("Form", "OCT Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("Form", "Visible Camera image", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("Form", "Intensity and Phase data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Save configuration", None, QtGui.QApplication.UnicodeUTF8))

import oct_gallery_resources_rc
