# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'microangio/assets/main_angio_capture.ui'
#
# Created: Thu Apr 21 10:45:03 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1425, 898)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtGui.QFrame(Form)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_main_angio_capture_left = QtGui.QFrame(self.frame)
        self.frame_main_angio_capture_left.setMinimumSize(QtCore.QSize(200, 500))
        self.frame_main_angio_capture_left.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_main_angio_capture_left.setStyleSheet("QFrame#frame_main_angio_capture_left  {\n"
" border: 1px solid #444;\n"
" padding: -8px;\n"
"}")
        self.frame_main_angio_capture_left.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_main_angio_capture_left.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_main_angio_capture_left.setObjectName("frame_main_angio_capture_left")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_main_angio_capture_left)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtGui.QFrame(self.frame_main_angio_capture_left)
        self.frame_5.setMinimumSize(QtCore.QSize(195, 200))
        self.frame_5.setMaximumSize(QtCore.QSize(195, 200))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_4 = QtGui.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtGui.QPushButton(self.frame_5)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 30, 31, 26))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtGui.QPushButton(self.frame_5)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 30, 31, 26))
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_8 = QtGui.QPushButton(self.frame_5)
        self.pushButton_8.setGeometry(QtCore.QRect(100, 30, 31, 26))
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtGui.QPushButton(self.frame_5)
        self.pushButton_9.setGeometry(QtCore.QRect(140, 30, 31, 26))
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.labelSnapshotThumbnail_3 = QtGui.QLabel(self.frame_5)
        self.labelSnapshotThumbnail_3.setGeometry(QtCore.QRect(20, 70, 161, 121))
        self.labelSnapshotThumbnail_3.setText("")
        self.labelSnapshotThumbnail_3.setPixmap(QtGui.QPixmap(":/website/images/oct_gallery/cat1_retina36s.jpg"))
        self.labelSnapshotThumbnail_3.setScaledContents(True)
        self.labelSnapshotThumbnail_3.setObjectName("labelSnapshotThumbnail_3")
        self.verticalLayout.addWidget(self.frame_5)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame_main_angio_capture_left)
        self.frame_main_angio_capture_center = QtGui.QFrame(self.frame)
        self.frame_main_angio_capture_center.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_main_angio_capture_center.setStyleSheet("QFrame#frame_main_angio_capture_center {\n"
" border: 1px solid #444;\n"
" padding: -8px;\n"
"}")
        self.frame_main_angio_capture_center.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_main_angio_capture_center.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_main_angio_capture_center.setObjectName("frame_main_angio_capture_center")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_main_angio_capture_center)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_19 = QtGui.QFrame(self.frame_main_angio_capture_center)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 750))
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 1677215))
        self.frame_19.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.label_55 = QtGui.QLabel(self.frame_19)
        self.label_55.setGeometry(QtCore.QRect(10, 400, 373, 337))
        self.label_55.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_55.setText("")
        self.label_55.setPixmap(QtGui.QPixmap(":/website/images/oct_gallery/retina_angiograph_03.jpg"))
        self.label_55.setScaledContents(True)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtGui.QLabel(self.frame_19)
        self.label_56.setGeometry(QtCore.QRect(11, 32, 373, 337))
        self.label_56.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_56.setText("")
        self.label_56.setPixmap(QtGui.QPixmap(":/website/images/oct_gallery/square_cat1_retina36s.jpg"))
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtGui.QLabel(self.frame_19)
        self.label_57.setGeometry(QtCore.QRect(390, 32, 373, 337))
        self.label_57.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_57.setText("")
        self.label_57.setPixmap(QtGui.QPixmap(":/website/images/oct_gallery/square_retina11.jpg"))
        self.label_57.setScaledContents(True)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtGui.QLabel(self.frame_19)
        self.label_58.setGeometry(QtCore.QRect(10, 380, 125, 16))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtGui.QLabel(self.frame_19)
        self.label_59.setGeometry(QtCore.QRect(390, 11, 158, 16))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtGui.QLabel(self.frame_19)
        self.label_60.setGeometry(QtCore.QRect(11, 11, 91, 16))
        self.label_60.setObjectName("label_60")
        self.gridLayout_2.addWidget(self.frame_19, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_main_angio_capture_center)
        self.frame_main_angio_capture_right = QtGui.QFrame(self.frame)
        self.frame_main_angio_capture_right.setMinimumSize(QtCore.QSize(200, 500))
        self.frame_main_angio_capture_right.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_main_angio_capture_right.setStyleSheet("QFrame#frame_main_angio_capture_right {\n"
" border: 1px solid #444;\n"
" padding: -8px;\n"
"}")
        self.frame_main_angio_capture_right.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_main_angio_capture_right.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_main_angio_capture_right.setObjectName("frame_main_angio_capture_right")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_main_angio_capture_right)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_15 = QtGui.QFrame(self.frame_main_angio_capture_right)
        self.frame_15.setMinimumSize(QtCore.QSize(195, 150))
        self.frame_15.setMaximumSize(QtCore.QSize(195, 200))
        self.frame_15.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_26 = QtGui.QLabel(self.frame_15)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_26.setObjectName("label_26")
        self.verticalScrollBar_2 = QtGui.QScrollBar(self.frame_15)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(20, 40, 16, 91))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.pushButton_12 = QtGui.QPushButton(self.frame_15)
        self.pushButton_12.setGeometry(QtCore.QRect(50, 40, 41, 27))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtGui.QPushButton(self.frame_15)
        self.pushButton_13.setGeometry(QtCore.QRect(50, 110, 41, 27))
        self.pushButton_13.setObjectName("pushButton_13")
        self.spinBox_20 = QtGui.QSpinBox(self.frame_15)
        self.spinBox_20.setGeometry(QtCore.QRect(50, 70, 91, 31))
        self.spinBox_20.setSuffix("")
        self.spinBox_20.setMaximum(10000)
        self.spinBox_20.setObjectName("spinBox_20")
        self.verticalLayout_3.addWidget(self.frame_15)
        self.frame_17 = QtGui.QFrame(self.frame_main_angio_capture_right)
        self.frame_17.setMinimumSize(QtCore.QSize(195, 100))
        self.frame_17.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_17.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_30 = QtGui.QLabel(self.frame_17)
        self.label_30.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_30.setObjectName("label_30")
        self.spinBox_23 = QtGui.QSpinBox(self.frame_17)
        self.spinBox_23.setGeometry(QtCore.QRect(150, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_23.setFont(font)
        self.spinBox_23.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_23.setObjectName("spinBox_23")
        self.label_31 = QtGui.QLabel(self.frame_17)
        self.label_31.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalSlider_13 = QtGui.QSlider(self.frame_17)
        self.horizontalSlider_13.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.horizontalSlider_13.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_13.setObjectName("horizontalSlider_13")
        self.horizontalSlider_14 = QtGui.QSlider(self.frame_17)
        self.horizontalSlider_14.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_14.setSliderPosition(77)
        self.horizontalSlider_14.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_14.setInvertedAppearance(False)
        self.horizontalSlider_14.setInvertedControls(False)
        self.horizontalSlider_14.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_14.setObjectName("horizontalSlider_14")
        self.label_32 = QtGui.QLabel(self.frame_17)
        self.label_32.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.spinBox_24 = QtGui.QSpinBox(self.frame_17)
        self.spinBox_24.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_24.setFont(font)
        self.spinBox_24.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_24.setProperty("value", 99)
        self.spinBox_24.setObjectName("spinBox_24")
        self.verticalLayout_3.addWidget(self.frame_17)
        self.label_24 = QtGui.QLabel(self.frame_main_angio_capture_right)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_3.addWidget(self.label_24)
        self.frame_13 = QtGui.QFrame(self.frame_main_angio_capture_right)
        self.frame_13.setMinimumSize(QtCore.QSize(195, 100))
        self.frame_13.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_21 = QtGui.QLabel(self.frame_13)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_21.setObjectName("label_21")
        self.spinBox_16 = QtGui.QSpinBox(self.frame_13)
        self.spinBox_16.setGeometry(QtCore.QRect(150, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_16.setFont(font)
        self.spinBox_16.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_16.setObjectName("spinBox_16")
        self.label_22 = QtGui.QLabel(self.frame_13)
        self.label_22.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalSlider_9 = QtGui.QSlider(self.frame_13)
        self.horizontalSlider_9.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.horizontalSlider_9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_9.setObjectName("horizontalSlider_9")
        self.horizontalSlider_10 = QtGui.QSlider(self.frame_13)
        self.horizontalSlider_10.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_10.setSliderPosition(77)
        self.horizontalSlider_10.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_10.setInvertedAppearance(False)
        self.horizontalSlider_10.setInvertedControls(False)
        self.horizontalSlider_10.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_10.setObjectName("horizontalSlider_10")
        self.label_23 = QtGui.QLabel(self.frame_13)
        self.label_23.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.spinBox_17 = QtGui.QSpinBox(self.frame_13)
        self.spinBox_17.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_17.setFont(font)
        self.spinBox_17.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_17.setProperty("value", 99)
        self.spinBox_17.setObjectName("spinBox_17")
        self.verticalLayout_3.addWidget(self.frame_13)
        self.frame_16 = QtGui.QFrame(self.frame_main_angio_capture_right)
        self.frame_16.setMinimumSize(QtCore.QSize(195, 100))
        self.frame_16.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_16.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_27 = QtGui.QLabel(self.frame_16)
        self.label_27.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_27.setObjectName("label_27")
        self.spinBox_21 = QtGui.QSpinBox(self.frame_16)
        self.spinBox_21.setGeometry(QtCore.QRect(150, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_21.setFont(font)
        self.spinBox_21.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_21.setObjectName("spinBox_21")
        self.label_28 = QtGui.QLabel(self.frame_16)
        self.label_28.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalSlider_11 = QtGui.QSlider(self.frame_16)
        self.horizontalSlider_11.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.horizontalSlider_11.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_11.setObjectName("horizontalSlider_11")
        self.horizontalSlider_12 = QtGui.QSlider(self.frame_16)
        self.horizontalSlider_12.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_12.setSliderPosition(77)
        self.horizontalSlider_12.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_12.setInvertedAppearance(False)
        self.horizontalSlider_12.setInvertedControls(False)
        self.horizontalSlider_12.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_12.setObjectName("horizontalSlider_12")
        self.label_29 = QtGui.QLabel(self.frame_16)
        self.label_29.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.spinBox_22 = QtGui.QSpinBox(self.frame_16)
        self.spinBox_22.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_22.setFont(font)
        self.spinBox_22.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_22.setProperty("value", 99)
        self.spinBox_22.setObjectName("spinBox_22")
        self.verticalLayout_3.addWidget(self.frame_16)
        spacerItem2 = QtGui.QSpacerItem(175, 49, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.frame_14 = QtGui.QFrame(self.frame_main_angio_capture_right)
        self.frame_14.setMinimumSize(QtCore.QSize(195, 150))
        self.frame_14.setMaximumSize(QtCore.QSize(195, 150))
        self.frame_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_25 = QtGui.QLabel(self.frame_14)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_25.setObjectName("label_25")
        self.pushButton_23 = QtGui.QPushButton(self.frame_14)
        self.pushButton_23.setGeometry(QtCore.QRect(80, 40, 41, 27))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtGui.QPushButton(self.frame_14)
        self.pushButton_24.setGeometry(QtCore.QRect(80, 80, 41, 27))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtGui.QPushButton(self.frame_14)
        self.pushButton_25.setGeometry(QtCore.QRect(130, 60, 41, 27))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtGui.QPushButton(self.frame_14)
        self.pushButton_26.setGeometry(QtCore.QRect(30, 60, 41, 27))
        self.pushButton_26.setObjectName("pushButton_26")
        self.spinBox_18 = QtGui.QSpinBox(self.frame_14)
        self.spinBox_18.setGeometry(QtCore.QRect(10, 120, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_18.setFont(font)
        self.spinBox_18.setSuffix("")
        self.spinBox_18.setMaximum(9999)
        self.spinBox_18.setProperty("value", 5555)
        self.spinBox_18.setObjectName("spinBox_18")
        self.spinBox_19 = QtGui.QSpinBox(self.frame_14)
        self.spinBox_19.setGeometry(QtCore.QRect(110, 120, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_19.setFont(font)
        self.spinBox_19.setSuffix("")
        self.spinBox_19.setMaximum(360)
        self.spinBox_19.setProperty("value", 300)
        self.spinBox_19.setObjectName("spinBox_19")
        self.verticalLayout_3.addWidget(self.frame_14)
        self.frame_3 = QtGui.QFrame(self.frame_main_angio_capture_right)
        self.frame_3.setMinimumSize(QtCore.QSize(195, 200))
        self.frame_3.setMaximumSize(QtCore.QSize(195, 200))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_6.setObjectName("label_6")
        self.labelSnapshotThumbnail_6 = QtGui.QLabel(self.frame_3)
        self.labelSnapshotThumbnail_6.setGeometry(QtCore.QRect(10, 30, 171, 141))
        self.labelSnapshotThumbnail_6.setText("")
        self.labelSnapshotThumbnail_6.setPixmap(QtGui.QPixmap(":/samples/images/vis_gallery/example_vis_camera_13.jpg"))
        self.labelSnapshotThumbnail_6.setScaledContents(True)
        self.labelSnapshotThumbnail_6.setObjectName("labelSnapshotThumbnail_6")
        self.label_20 = QtGui.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(13, 180, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.spinBox_15 = QtGui.QSpinBox(self.frame_3)
        self.spinBox_15.setGeometry(QtCore.QRect(150, 180, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_15.setFont(font)
        self.spinBox_15.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_15.setObjectName("spinBox_15")
        self.horizontalSlider_8 = QtGui.QSlider(self.frame_3)
        self.horizontalSlider_8.setGeometry(QtCore.QRect(70, 180, 71, 16))
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName("horizontalSlider_8")
        self.verticalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame_main_angio_capture_right)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Snapshot", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("Form", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("Form", "De", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("Form", "Cp", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("Form", "Ev", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("Form", "Angiograph preview", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("Form", "Continuous scan preview", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("Form", "Center B-scan", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Form", "Reference Arm", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("Form", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("Form", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_20.setPrefix(QtGui.QApplication.translate("Form", "Position: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Form", "OCT Image Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Form", "Min. Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Form", "Max. Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Form", "Colormap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Form", "Dispersion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Form", "Coeff. B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Form", "Oceff. C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Form", "Polarization", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Form", "Half Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Form", "Quar. Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Form", "Scan line control", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_23.setText(QtGui.QApplication.translate("Form", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_24.setText(QtGui.QApplication.translate("Form", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_25.setText(QtGui.QApplication.translate("Form", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_26.setText(QtGui.QApplication.translate("Form", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_18.setPrefix(QtGui.QApplication.translate("Form", "Length: ", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_19.setPrefix(QtGui.QApplication.translate("Form", "Angle: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Visible Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Form", "Exposure", None, QtGui.QApplication.UnicodeUTF8))

import oct_gallery_resources_rc
import vis_gallery_resources_rc
import colormap_resources_rc
