# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'microangio/assets/microangio_layout.ui'
#
# Created: Mon Apr 25 10:20:07 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(975, 940)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidgetCenter_3 = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidgetCenter_3.setMinimumSize(QtCore.QSize(0, 60))
        self.stackedWidgetCenter_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.stackedWidgetCenter_3.setLineWidth(0)
        self.stackedWidgetCenter_3.setObjectName("stackedWidgetCenter_3")
        self.page_9 = QtGui.QWidget()
        self.page_9.setObjectName("page_9")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_5 = QtGui.QFrame(self.page_9)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtGui.QLabel(self.frame_5)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/logos/images/logos/110x36_wp_angio.png"))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.comboBox_3 = QtGui.QComboBox(self.frame_5)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.frame_6 = QtGui.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_3 = QtGui.QPushButton(self.frame_6)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_9.addWidget(self.pushButton_3)
        self.pushButton_7 = QtGui.QPushButton(self.frame_6)
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setChecked(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_9.addWidget(self.pushButton_7)
        self.pushButton_8 = QtGui.QPushButton(self.frame_6)
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_9.addWidget(self.pushButton_8)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7.addWidget(self.frame_6)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.stackedWidgetCenter_3.addWidget(self.page_9)
        self.page_10 = QtGui.QWidget()
        self.page_10.setObjectName("page_10")
        self.label_7 = QtGui.QLabel(self.page_10)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 221, 41))
        self.label_7.setObjectName("label_7")
        self.stackedWidgetCenter_3.addWidget(self.page_10)
        self.gridLayout.addWidget(self.stackedWidgetCenter_3, 0, 0, 1, 3)
        self.stackedWidgetCenter_4 = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidgetCenter_4.setMinimumSize(QtCore.QSize(210, 50))
        self.stackedWidgetCenter_4.setMaximumSize(QtCore.QSize(210, 16777215))
        self.stackedWidgetCenter_4.setObjectName("stackedWidgetCenter_4")
        self.page_13 = QtGui.QWidget()
        self.page_13.setObjectName("page_13")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page_13)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtGui.QFrame(self.page_13)
        self.frame.setMinimumSize(QtCore.QSize(200, 0))
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 10, 195, 211))
        self.frame_3.setMinimumSize(QtCore.QSize(195, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(195, 16777215))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_12 = QtGui.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_12.setObjectName("label_12")
        self.pushButton_4 = QtGui.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 30, 31, 26))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtGui.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(60, 30, 31, 26))
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_9 = QtGui.QPushButton(self.frame_3)
        self.pushButton_9.setGeometry(QtCore.QRect(100, 30, 31, 26))
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtGui.QPushButton(self.frame_3)
        self.pushButton_10.setGeometry(QtCore.QRect(140, 30, 31, 26))
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.labelSnapshotThumbnail_3 = QtGui.QLabel(self.frame_3)
        self.labelSnapshotThumbnail_3.setGeometry(QtCore.QRect(20, 70, 161, 121))
        self.labelSnapshotThumbnail_3.setText("")
        self.labelSnapshotThumbnail_3.setPixmap(QtGui.QPixmap(":/website/images/oct_gallery/fingernail_fullsize.png"))
        self.labelSnapshotThumbnail_3.setScaledContents(True)
        self.labelSnapshotThumbnail_3.setObjectName("labelSnapshotThumbnail_3")
        self.verticalLayout_6.addWidget(self.frame)
        self.stackedWidgetCenter_4.addWidget(self.page_13)
        self.page_17 = QtGui.QWidget()
        self.page_17.setObjectName("page_17")
        self.label_59 = QtGui.QLabel(self.page_17)
        self.label_59.setGeometry(QtCore.QRect(30, 80, 151, 111))
        self.label_59.setObjectName("label_59")
        self.stackedWidgetCenter_4.addWidget(self.page_17)
        self.page_18 = QtGui.QWidget()
        self.page_18.setObjectName("page_18")
        self.frame_32 = QtGui.QFrame(self.page_18)
        self.frame_32.setGeometry(QtCore.QRect(0, 20, 195, 121))
        self.frame_32.setMinimumSize(QtCore.QSize(195, 0))
        self.frame_32.setMaximumSize(QtCore.QSize(195, 16777215))
        self.frame_32.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.label_60 = QtGui.QLabel(self.frame_32)
        self.label_60.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtGui.QLabel(self.frame_32)
        self.label_61.setGeometry(QtCore.QRect(20, 40, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.pushButton_39 = QtGui.QPushButton(self.frame_32)
        self.pushButton_39.setGeometry(QtCore.QRect(20, 70, 31, 26))
        self.pushButton_39.setCheckable(True)
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtGui.QPushButton(self.frame_32)
        self.pushButton_40.setGeometry(QtCore.QRect(60, 70, 31, 26))
        self.pushButton_40.setCheckable(True)
        self.pushButton_40.setObjectName("pushButton_40")
        self.frame_33 = QtGui.QFrame(self.page_18)
        self.frame_33.setGeometry(QtCore.QRect(0, 150, 195, 251))
        self.frame_33.setMinimumSize(QtCore.QSize(195, 0))
        self.frame_33.setMaximumSize(QtCore.QSize(195, 16777215))
        self.frame_33.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.label_62 = QtGui.QLabel(self.frame_33)
        self.label_62.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_62.setObjectName("label_62")
        self.labelSnapshotThumbnail_2 = QtGui.QLabel(self.frame_33)
        self.labelSnapshotThumbnail_2.setGeometry(QtCore.QRect(20, 60, 161, 121))
        self.labelSnapshotThumbnail_2.setText("")
        self.labelSnapshotThumbnail_2.setPixmap(QtGui.QPixmap(":/website/images/oct_gallery/raw_image_pyqtgraph_plot.png"))
        self.labelSnapshotThumbnail_2.setScaledContents(True)
        self.labelSnapshotThumbnail_2.setObjectName("labelSnapshotThumbnail_2")
        self.label_63 = QtGui.QLabel(self.frame_33)
        self.label_63.setGeometry(QtCore.QRect(20, 40, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.pushButton_41 = QtGui.QPushButton(self.frame_33)
        self.pushButton_41.setGeometry(QtCore.QRect(20, 190, 31, 26))
        self.pushButton_41.setCheckable(True)
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtGui.QPushButton(self.frame_33)
        self.pushButton_42.setGeometry(QtCore.QRect(60, 190, 31, 26))
        self.pushButton_42.setCheckable(True)
        self.pushButton_42.setObjectName("pushButton_42")
        self.stackedWidgetCenter_4.addWidget(self.page_18)
        self.page_14 = QtGui.QWidget()
        self.page_14.setObjectName("page_14")
        self.label_9 = QtGui.QLabel(self.page_14)
        self.label_9.setGeometry(QtCore.QRect(20, 20, 131, 41))
        self.label_9.setObjectName("label_9")
        self.stackedWidgetCenter_4.addWidget(self.page_14)
        self.gridLayout.addWidget(self.stackedWidgetCenter_4, 1, 0, 2, 1)
        self.stackedWidgetCenter_5 = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidgetCenter_5.setMinimumSize(QtCore.QSize(210, 50))
        self.stackedWidgetCenter_5.setMaximumSize(QtCore.QSize(210, 16777215))
        self.stackedWidgetCenter_5.setObjectName("stackedWidgetCenter_5")
        self.page_15 = QtGui.QWidget()
        self.page_15.setObjectName("page_15")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_2 = QtGui.QFrame(self.page_15)
        self.frame_2.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_10 = QtGui.QFrame(self.frame_2)
        self.frame_10.setMinimumSize(QtCore.QSize(195, 150))
        self.frame_10.setMaximumSize(QtCore.QSize(195, 200))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_11 = QtGui.QLabel(self.frame_10)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_11.setObjectName("label_11")
        self.verticalScrollBar = QtGui.QScrollBar(self.frame_10)
        self.verticalScrollBar.setGeometry(QtCore.QRect(20, 40, 16, 91))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.pushButton_19 = QtGui.QPushButton(self.frame_10)
        self.pushButton_19.setGeometry(QtCore.QRect(50, 40, 41, 27))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtGui.QPushButton(self.frame_10)
        self.pushButton_20.setGeometry(QtCore.QRect(50, 110, 41, 27))
        self.pushButton_20.setObjectName("pushButton_20")
        self.spinBox_6 = QtGui.QSpinBox(self.frame_10)
        self.spinBox_6.setGeometry(QtCore.QRect(50, 70, 91, 31))
        self.spinBox_6.setSuffix("")
        self.spinBox_6.setMaximum(10000)
        self.spinBox_6.setObjectName("spinBox_6")
        self.verticalLayout_2.addWidget(self.frame_10)
        self.frame_11 = QtGui.QFrame(self.frame_2)
        self.frame_11.setMinimumSize(QtCore.QSize(195, 100))
        self.frame_11.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_13 = QtGui.QLabel(self.frame_11)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_13.setObjectName("label_13")
        self.spinBox_7 = QtGui.QSpinBox(self.frame_11)
        self.spinBox_7.setGeometry(QtCore.QRect(150, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_7.setFont(font)
        self.spinBox_7.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_7.setObjectName("spinBox_7")
        self.label_15 = QtGui.QLabel(self.frame_11)
        self.label_15.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalSlider_2 = QtGui.QSlider(self.frame_11)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtGui.QSlider(self.frame_11)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_3.setSliderPosition(77)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setInvertedAppearance(False)
        self.horizontalSlider_3.setInvertedControls(False)
        self.horizontalSlider_3.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_16 = QtGui.QLabel(self.frame_11)
        self.label_16.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.spinBox_8 = QtGui.QSpinBox(self.frame_11)
        self.spinBox_8.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_8.setFont(font)
        self.spinBox_8.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_8.setProperty("value", 99)
        self.spinBox_8.setObjectName("spinBox_8")
        self.verticalLayout_2.addWidget(self.frame_11)
        self.frame_12 = QtGui.QFrame(self.frame_2)
        self.frame_12.setMinimumSize(QtCore.QSize(195, 70))
        self.frame_12.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_17 = QtGui.QLabel(self.frame_12)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_17.setObjectName("label_17")
        self.comboBox_4 = QtGui.QComboBox(self.frame_12)
        self.comboBox_4.setGeometry(QtCore.QRect(10, 30, 71, 27))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.labelSnapshotThumbnail_5 = QtGui.QLabel(self.frame_12)
        self.labelSnapshotThumbnail_5.setGeometry(QtCore.QRect(90, 30, 24, 24))
        self.labelSnapshotThumbnail_5.setText("")
        self.labelSnapshotThumbnail_5.setPixmap(QtGui.QPixmap(":/thumbnails/images/colormaps/gray.jpg"))
        self.labelSnapshotThumbnail_5.setScaledContents(True)
        self.labelSnapshotThumbnail_5.setObjectName("labelSnapshotThumbnail_5")
        self.verticalLayout_2.addWidget(self.frame_12)
        self.frame_13 = QtGui.QFrame(self.frame_2)
        self.frame_13.setMinimumSize(QtCore.QSize(195, 100))
        self.frame_13.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_18 = QtGui.QLabel(self.frame_13)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_18.setObjectName("label_18")
        self.spinBox_11 = QtGui.QSpinBox(self.frame_13)
        self.spinBox_11.setGeometry(QtCore.QRect(150, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_11.setFont(font)
        self.spinBox_11.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_11.setObjectName("spinBox_11")
        self.label_19 = QtGui.QLabel(self.frame_13)
        self.label_19.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalSlider_4 = QtGui.QSlider(self.frame_13)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalSlider_5 = QtGui.QSlider(self.frame_13)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_5.setSliderPosition(77)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setInvertedAppearance(False)
        self.horizontalSlider_5.setInvertedControls(False)
        self.horizontalSlider_5.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.label_20 = QtGui.QLabel(self.frame_13)
        self.label_20.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.spinBox_12 = QtGui.QSpinBox(self.frame_13)
        self.spinBox_12.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_12.setFont(font)
        self.spinBox_12.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_12.setProperty("value", 99)
        self.spinBox_12.setObjectName("spinBox_12")
        self.verticalLayout_2.addWidget(self.frame_13)
        self.frame_14 = QtGui.QFrame(self.frame_2)
        self.frame_14.setMinimumSize(QtCore.QSize(195, 100))
        self.frame_14.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_21 = QtGui.QLabel(self.frame_14)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_21.setObjectName("label_21")
        self.spinBox_13 = QtGui.QSpinBox(self.frame_14)
        self.spinBox_13.setGeometry(QtCore.QRect(150, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_13.setFont(font)
        self.spinBox_13.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_13.setObjectName("spinBox_13")
        self.label_22 = QtGui.QLabel(self.frame_14)
        self.label_22.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalSlider_6 = QtGui.QSlider(self.frame_14)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.horizontalSlider_7 = QtGui.QSlider(self.frame_14)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_7.setSliderPosition(77)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setInvertedAppearance(False)
        self.horizontalSlider_7.setInvertedControls(False)
        self.horizontalSlider_7.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.label_23 = QtGui.QLabel(self.frame_14)
        self.label_23.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.spinBox_14 = QtGui.QSpinBox(self.frame_14)
        self.spinBox_14.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_14.setFont(font)
        self.spinBox_14.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_14.setProperty("value", 99)
        self.spinBox_14.setObjectName("spinBox_14")
        self.verticalLayout_2.addWidget(self.frame_14)
        spacerItem2 = QtGui.QSpacerItem(20, 68, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.frame_15 = QtGui.QFrame(self.frame_2)
        self.frame_15.setMinimumSize(QtCore.QSize(195, 150))
        self.frame_15.setMaximumSize(QtCore.QSize(195, 150))
        self.frame_15.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_24 = QtGui.QLabel(self.frame_15)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_24.setObjectName("label_24")
        self.pushButton_21 = QtGui.QPushButton(self.frame_15)
        self.pushButton_21.setGeometry(QtCore.QRect(80, 40, 41, 27))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtGui.QPushButton(self.frame_15)
        self.pushButton_22.setGeometry(QtCore.QRect(80, 80, 41, 27))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtGui.QPushButton(self.frame_15)
        self.pushButton_23.setGeometry(QtCore.QRect(130, 60, 41, 27))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtGui.QPushButton(self.frame_15)
        self.pushButton_24.setGeometry(QtCore.QRect(30, 60, 41, 27))
        self.pushButton_24.setObjectName("pushButton_24")
        self.spinBox_9 = QtGui.QSpinBox(self.frame_15)
        self.spinBox_9.setGeometry(QtCore.QRect(10, 120, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_9.setFont(font)
        self.spinBox_9.setSuffix("")
        self.spinBox_9.setMaximum(9999)
        self.spinBox_9.setProperty("value", 5555)
        self.spinBox_9.setObjectName("spinBox_9")
        self.spinBox_10 = QtGui.QSpinBox(self.frame_15)
        self.spinBox_10.setGeometry(QtCore.QRect(110, 120, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_10.setFont(font)
        self.spinBox_10.setSuffix("")
        self.spinBox_10.setMaximum(360)
        self.spinBox_10.setProperty("value", 300)
        self.spinBox_10.setObjectName("spinBox_10")
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame_16 = QtGui.QFrame(self.frame_2)
        self.frame_16.setMinimumSize(QtCore.QSize(195, 200))
        self.frame_16.setMaximumSize(QtCore.QSize(195, 200))
        self.frame_16.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_5 = QtGui.QLabel(self.frame_16)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_5.setObjectName("label_5")
        self.labelSnapshotThumbnail_4 = QtGui.QLabel(self.frame_16)
        self.labelSnapshotThumbnail_4.setGeometry(QtCore.QRect(10, 30, 171, 141))
        self.labelSnapshotThumbnail_4.setText("")
        self.labelSnapshotThumbnail_4.setPixmap(QtGui.QPixmap(":/samples/images/vis_gallery/example_vis_camera_13.jpg"))
        self.labelSnapshotThumbnail_4.setScaledContents(True)
        self.labelSnapshotThumbnail_4.setObjectName("labelSnapshotThumbnail_4")
        self.label_25 = QtGui.QLabel(self.frame_16)
        self.label_25.setGeometry(QtCore.QRect(13, 180, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.spinBox_5 = QtGui.QSpinBox(self.frame_16)
        self.spinBox_5.setGeometry(QtCore.QRect(150, 180, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_5.setFont(font)
        self.spinBox_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalSlider = QtGui.QSlider(self.frame_16)
        self.horizontalSlider.setGeometry(QtCore.QRect(70, 180, 71, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.frame_16)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.stackedWidgetCenter_5.addWidget(self.page_15)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_14 = QtGui.QLabel(self.page_5)
        self.label_14.setGeometry(QtCore.QRect(10, 80, 141, 41))
        self.label_14.setObjectName("label_14")
        self.stackedWidgetCenter_5.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.page_6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_8 = QtGui.QFrame(self.page_6)
        self.frame_8.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_26 = QtGui.QFrame(self.frame_8)
        self.frame_26.setMinimumSize(QtCore.QSize(195, 200))
        self.frame_26.setMaximumSize(QtCore.QSize(195, 200))
        self.frame_26.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.label_50 = QtGui.QLabel(self.frame_26)
        self.label_50.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_50.setObjectName("label_50")
        self.spinBox_24 = QtGui.QSpinBox(self.frame_26)
        self.spinBox_24.setGeometry(QtCore.QRect(150, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_24.setFont(font)
        self.spinBox_24.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_24.setProperty("value", 50)
        self.spinBox_24.setObjectName("spinBox_24")
        self.label_51 = QtGui.QLabel(self.frame_26)
        self.label_51.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.horizontalSlider_14 = QtGui.QSlider(self.frame_26)
        self.horizontalSlider_14.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.horizontalSlider_14.setProperty("value", 50)
        self.horizontalSlider_14.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_14.setObjectName("horizontalSlider_14")
        self.horizontalSlider_18 = QtGui.QSlider(self.frame_26)
        self.horizontalSlider_18.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_18.setSliderPosition(77)
        self.horizontalSlider_18.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_18.setInvertedAppearance(False)
        self.horizontalSlider_18.setInvertedControls(False)
        self.horizontalSlider_18.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_18.setObjectName("horizontalSlider_18")
        self.label_52 = QtGui.QLabel(self.frame_26)
        self.label_52.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.spinBox_28 = QtGui.QSpinBox(self.frame_26)
        self.spinBox_28.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_28.setFont(font)
        self.spinBox_28.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_28.setMaximum(100)
        self.spinBox_28.setProperty("value", 100)
        self.spinBox_28.setObjectName("spinBox_28")
        self.spinBox_29 = QtGui.QSpinBox(self.frame_26)
        self.spinBox_29.setGeometry(QtCore.QRect(150, 100, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_29.setFont(font)
        self.spinBox_29.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_29.setMaximum(100)
        self.spinBox_29.setProperty("value", 100)
        self.spinBox_29.setObjectName("spinBox_29")
        self.horizontalSlider_19 = QtGui.QSlider(self.frame_26)
        self.horizontalSlider_19.setGeometry(QtCore.QRect(70, 100, 71, 16))
        self.horizontalSlider_19.setSliderPosition(77)
        self.horizontalSlider_19.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_19.setInvertedAppearance(False)
        self.horizontalSlider_19.setInvertedControls(False)
        self.horizontalSlider_19.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_19.setObjectName("horizontalSlider_19")
        self.label_53 = QtGui.QLabel(self.frame_26)
        self.label_53.setGeometry(QtCore.QRect(10, 100, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.spinBox_38 = QtGui.QSpinBox(self.frame_26)
        self.spinBox_38.setGeometry(QtCore.QRect(150, 130, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_38.setFont(font)
        self.spinBox_38.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_38.setMaximum(100)
        self.spinBox_38.setProperty("value", 100)
        self.spinBox_38.setObjectName("spinBox_38")
        self.horizontalSlider_28 = QtGui.QSlider(self.frame_26)
        self.horizontalSlider_28.setGeometry(QtCore.QRect(70, 130, 71, 16))
        self.horizontalSlider_28.setSliderPosition(77)
        self.horizontalSlider_28.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_28.setInvertedAppearance(False)
        self.horizontalSlider_28.setInvertedControls(False)
        self.horizontalSlider_28.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_28.setObjectName("horizontalSlider_28")
        self.label_54 = QtGui.QLabel(self.frame_26)
        self.label_54.setGeometry(QtCore.QRect(10, 130, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_10.addWidget(self.frame_26)
        self.frame_27 = QtGui.QFrame(self.frame_8)
        self.frame_27.setMinimumSize(QtCore.QSize(195, 150))
        self.frame_27.setMaximumSize(QtCore.QSize(195, 200))
        self.frame_27.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.label_55 = QtGui.QLabel(self.frame_27)
        self.label_55.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_55.setObjectName("label_55")
        self.verticalScrollBar_5 = QtGui.QScrollBar(self.frame_27)
        self.verticalScrollBar_5.setGeometry(QtCore.QRect(20, 40, 16, 91))
        self.verticalScrollBar_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_5.setObjectName("verticalScrollBar_5")
        self.pushButton_30 = QtGui.QPushButton(self.frame_27)
        self.pushButton_30.setGeometry(QtCore.QRect(50, 40, 41, 27))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtGui.QPushButton(self.frame_27)
        self.pushButton_31.setGeometry(QtCore.QRect(50, 110, 41, 27))
        self.pushButton_31.setObjectName("pushButton_31")
        self.spinBox_30 = QtGui.QSpinBox(self.frame_27)
        self.spinBox_30.setGeometry(QtCore.QRect(50, 70, 91, 31))
        self.spinBox_30.setSuffix("")
        self.spinBox_30.setMaximum(10000)
        self.spinBox_30.setObjectName("spinBox_30")
        self.verticalLayout_10.addWidget(self.frame_27)
        self.frame_28 = QtGui.QFrame(self.frame_8)
        self.frame_28.setMinimumSize(QtCore.QSize(195, 100))
        self.frame_28.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_28.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.label_56 = QtGui.QLabel(self.frame_28)
        self.label_56.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_56.setObjectName("label_56")
        self.pushButton_32 = QtGui.QPushButton(self.frame_28)
        self.pushButton_32.setGeometry(QtCore.QRect(10, 30, 51, 27))
        self.pushButton_32.setObjectName("pushButton_32")
        self.spinBox_39 = QtGui.QSpinBox(self.frame_28)
        self.spinBox_39.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_39.setFont(font)
        self.spinBox_39.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_39.setMaximum(100)
        self.spinBox_39.setProperty("value", 100)
        self.spinBox_39.setObjectName("spinBox_39")
        self.horizontalSlider_29 = QtGui.QSlider(self.frame_28)
        self.horizontalSlider_29.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_29.setSliderPosition(77)
        self.horizontalSlider_29.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_29.setInvertedAppearance(False)
        self.horizontalSlider_29.setInvertedControls(False)
        self.horizontalSlider_29.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_29.setObjectName("horizontalSlider_29")
        self.label_57 = QtGui.QLabel(self.frame_28)
        self.label_57.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_10.addWidget(self.frame_28)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.frame_34 = QtGui.QFrame(self.frame_8)
        self.frame_34.setMinimumSize(QtCore.QSize(195, 200))
        self.frame_34.setMaximumSize(QtCore.QSize(195, 200))
        self.frame_34.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.label_64 = QtGui.QLabel(self.frame_34)
        self.label_64.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_64.setObjectName("label_64")
        self.labelSnapshotThumbnail_6 = QtGui.QLabel(self.frame_34)
        self.labelSnapshotThumbnail_6.setGeometry(QtCore.QRect(10, 30, 171, 141))
        self.labelSnapshotThumbnail_6.setText("")
        self.labelSnapshotThumbnail_6.setPixmap(QtGui.QPixmap(":/samples/images/vis_gallery/example_vis_camera_13.jpg"))
        self.labelSnapshotThumbnail_6.setScaledContents(True)
        self.labelSnapshotThumbnail_6.setObjectName("labelSnapshotThumbnail_6")
        self.label_65 = QtGui.QLabel(self.frame_34)
        self.label_65.setGeometry(QtCore.QRect(13, 180, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.spinBox_31 = QtGui.QSpinBox(self.frame_34)
        self.spinBox_31.setGeometry(QtCore.QRect(150, 180, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_31.setFont(font)
        self.spinBox_31.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_31.setObjectName("spinBox_31")
        self.horizontalSlider_20 = QtGui.QSlider(self.frame_34)
        self.horizontalSlider_20.setGeometry(QtCore.QRect(70, 180, 71, 16))
        self.horizontalSlider_20.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_20.setObjectName("horizontalSlider_20")
        self.verticalLayout_10.addWidget(self.frame_34)
        self.verticalLayout_11.addWidget(self.frame_8)
        self.stackedWidgetCenter_5.addWidget(self.page_6)
        self.page_16 = QtGui.QWidget()
        self.page_16.setObjectName("page_16")
        self.label_10 = QtGui.QLabel(self.page_16)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 131, 41))
        self.label_10.setObjectName("label_10")
        self.stackedWidgetCenter_5.addWidget(self.page_16)
        self.gridLayout.addWidget(self.stackedWidgetCenter_5, 1, 2, 2, 1)
        self.stackedWidgetCenter = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidgetCenter.setObjectName("stackedWidgetCenter")
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameCenterArea = QtGui.QFrame(self.page_3)
        self.frameCenterArea.setMinimumSize(QtCore.QSize(200, 0))
        self.frameCenterArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameCenterArea.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCenterArea.setObjectName("frameCenterArea")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frameCenterArea)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtGui.QFrame(self.frameCenterArea)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setPixmap(QtGui.QPixmap(":/website/images/oct_gallery/cat1_retina36s.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.frame_4)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frameCenterArea)
        self.stackedWidgetCenter.addWidget(self.page_3)
        self.page_19 = QtGui.QWidget()
        self.page_19.setObjectName("page_19")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.page_19)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frameCenterArea_3 = QtGui.QFrame(self.page_19)
        self.frameCenterArea_3.setMinimumSize(QtCore.QSize(200, 0))
        self.frameCenterArea_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameCenterArea_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCenterArea_3.setObjectName("frameCenterArea_3")
        self.frame_35 = QtGui.QFrame(self.frameCenterArea_3)
        self.frame_35.setGeometry(QtCore.QRect(110, 40, 441, 121))
        self.frame_35.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.label_66 = QtGui.QLabel(self.frame_35)
        self.label_66.setGeometry(QtCore.QRect(30, 20, 171, 16))
        self.label_66.setObjectName("label_66")
        self.pushButton_43 = QtGui.QPushButton(self.frame_35)
        self.pushButton_43.setGeometry(QtCore.QRect(330, 40, 91, 61))
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_44 = QtGui.QPushButton(self.frame_35)
        self.pushButton_44.setGeometry(QtCore.QRect(30, 40, 91, 61))
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_45 = QtGui.QPushButton(self.frame_35)
        self.pushButton_45.setGeometry(QtCore.QRect(230, 40, 91, 61))
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_46 = QtGui.QPushButton(self.frame_35)
        self.pushButton_46.setGeometry(QtCore.QRect(130, 40, 91, 61))
        self.pushButton_46.setObjectName("pushButton_46")
        self.frame_36 = QtGui.QFrame(self.frameCenterArea_3)
        self.frame_36.setGeometry(QtCore.QRect(110, 170, 441, 121))
        self.frame_36.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.label_67 = QtGui.QLabel(self.frame_36)
        self.label_67.setGeometry(QtCore.QRect(30, 20, 171, 16))
        self.label_67.setObjectName("label_67")
        self.pushButton_47 = QtGui.QPushButton(self.frame_36)
        self.pushButton_47.setGeometry(QtCore.QRect(30, 40, 91, 61))
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_48 = QtGui.QPushButton(self.frame_36)
        self.pushButton_48.setGeometry(QtCore.QRect(130, 40, 91, 61))
        self.pushButton_48.setObjectName("pushButton_48")
        self.frame_37 = QtGui.QFrame(self.frameCenterArea_3)
        self.frame_37.setGeometry(QtCore.QRect(110, 300, 441, 121))
        self.frame_37.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.label_68 = QtGui.QLabel(self.frame_37)
        self.label_68.setGeometry(QtCore.QRect(30, 20, 171, 16))
        self.label_68.setObjectName("label_68")
        self.pushButton_49 = QtGui.QPushButton(self.frame_37)
        self.pushButton_49.setGeometry(QtCore.QRect(30, 40, 91, 61))
        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_50 = QtGui.QPushButton(self.frame_37)
        self.pushButton_50.setGeometry(QtCore.QRect(230, 40, 91, 61))
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_51 = QtGui.QPushButton(self.frame_37)
        self.pushButton_51.setGeometry(QtCore.QRect(130, 40, 91, 61))
        self.pushButton_51.setObjectName("pushButton_51")
        self.frame_38 = QtGui.QFrame(self.frameCenterArea_3)
        self.frame_38.setGeometry(QtCore.QRect(170, 430, 381, 219))
        self.frame_38.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_38)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_69 = QtGui.QLabel(self.frame_38)
        self.label_69.setObjectName("label_69")
        self.gridLayout_4.addWidget(self.label_69, 0, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.frame_38)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.checkBox, 1, 0, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.frame_38)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_4.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.frame_38)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_4.addWidget(self.checkBox_4, 3, 0, 1, 1)
        self.checkBox_5 = QtGui.QCheckBox(self.frame_38)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_4.addWidget(self.checkBox_5, 4, 0, 1, 1)
        self.checkBox_6 = QtGui.QCheckBox(self.frame_38)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_4.addWidget(self.checkBox_6, 5, 0, 1, 1)
        self.checkBox_7 = QtGui.QCheckBox(self.frame_38)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_4.addWidget(self.checkBox_7, 6, 0, 1, 1)
        self.checkBox_8 = QtGui.QCheckBox(self.frame_38)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_4.addWidget(self.checkBox_8, 7, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.frameCenterArea_3)
        self.stackedWidgetCenter.addWidget(self.page_19)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(90, 30, 321, 16))
        self.label_3.setObjectName("label_3")
        self.stackedWidgetCenter.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frameCenterArea_2 = QtGui.QFrame(self.page_2)
        self.frameCenterArea_2.setMinimumSize(QtCore.QSize(200, 0))
        self.frameCenterArea_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameCenterArea_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCenterArea_2.setObjectName("frameCenterArea_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.frameCenterArea_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtGui.QLabel(self.frameCenterArea_2)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/website/images/oct_gallery/raw_image_pyqtgraph_plot.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frameCenterArea_2, 0, 0, 1, 1)
        self.stackedWidgetCenter.addWidget(self.page_2)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.label = QtGui.QLabel(self.page_4)
        self.label.setGeometry(QtCore.QRect(20, 20, 221, 41))
        self.label.setObjectName("label")
        self.stackedWidgetCenter.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidgetCenter, 2, 1, 1, 1)
        self.stackedWidgetCenter_2 = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidgetCenter_2.setMinimumSize(QtCore.QSize(0, 50))
        self.stackedWidgetCenter_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stackedWidgetCenter_2.setObjectName("stackedWidgetCenter_2")
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtGui.QFrame(self.page_7)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.frame_9 = QtGui.QFrame(self.frame_7)
        self.frame_9.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.frame_9)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_5 = QtGui.QPushButton(self.frame_9)
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setChecked(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_15.addWidget(self.pushButton_5)
        self.pushButton_15 = QtGui.QPushButton(self.frame_9)
        self.pushButton_15.setCheckable(True)
        self.pushButton_15.setChecked(False)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_15.addWidget(self.pushButton_15)
        self.pushButton_16 = QtGui.QPushButton(self.frame_9)
        self.pushButton_16.setCheckable(False)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_15.addWidget(self.pushButton_16)
        self.pushButton_17 = QtGui.QPushButton(self.frame_9)
        self.pushButton_17.setCheckable(True)
        self.pushButton_17.setChecked(False)
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_15.addWidget(self.pushButton_17)
        self.pushButton_18 = QtGui.QPushButton(self.frame_9)
        self.pushButton_18.setCheckable(False)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_15.addWidget(self.pushButton_18)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13.addWidget(self.frame_9)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.stackedWidgetCenter_2.addWidget(self.page_7)
        self.page_11 = QtGui.QWidget()
        self.page_11.setObjectName("page_11")
        self.label_58 = QtGui.QLabel(self.page_11)
        self.label_58.setGeometry(QtCore.QRect(90, 30, 171, 16))
        self.label_58.setObjectName("label_58")
        self.stackedWidgetCenter_2.addWidget(self.page_11)
        self.page_12 = QtGui.QWidget()
        self.page_12.setObjectName("page_12")
        self.frame_29 = QtGui.QFrame(self.page_12)
        self.frame_29.setGeometry(QtCore.QRect(-10, 10, 741, 45))
        self.frame_29.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_29.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_29.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.frame_29)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.frame_31 = QtGui.QFrame(self.frame_29)
        self.frame_31.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_31.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_31.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_31.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.frame_31)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton_36 = QtGui.QPushButton(self.frame_31)
        self.pushButton_36.setCheckable(True)
        self.pushButton_36.setChecked(True)
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_18.addWidget(self.pushButton_36)
        self.pushButton_37 = QtGui.QPushButton(self.frame_31)
        self.pushButton_37.setCheckable(True)
        self.pushButton_37.setChecked(False)
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_18.addWidget(self.pushButton_37)
        self.pushButton_38 = QtGui.QPushButton(self.frame_31)
        self.pushButton_38.setCheckable(True)
        self.pushButton_38.setChecked(False)
        self.pushButton_38.setObjectName("pushButton_38")
        self.horizontalLayout_18.addWidget(self.pushButton_38)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_16.addWidget(self.frame_31)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        self.stackedWidgetCenter_2.addWidget(self.page_12)
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName("page_8")
        self.label_6 = QtGui.QLabel(self.page_8)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 221, 41))
        self.label_6.setObjectName("label_6")
        self.stackedWidgetCenter_2.addWidget(self.page_8)
        self.gridLayout.addWidget(self.stackedWidgetCenter_2, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidgetCenter_3.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(0)
        self.stackedWidgetCenter_4.setCurrentIndex(2)
        self.stackedWidgetCenter_5.setCurrentIndex(2)
        self.comboBox_4.setCurrentIndex(0)
        self.stackedWidgetCenter.setCurrentIndex(1)
        self.stackedWidgetCenter_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(0, QtGui.QApplication.translate("MainWindow", "Hardware", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(1, QtGui.QApplication.translate("MainWindow", "3D OCT", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(2, QtGui.QApplication.translate("MainWindow", "OCT", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(3, QtGui.QApplication.translate("MainWindow", "Angiography", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", "Capture", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("MainWindow", "Evaluate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Top area", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Snapshot", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("MainWindow", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Hardware configuration </p><p>save area</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("MainWindow", "Current Configuration:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("MainWindow", "LA OCT Config", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_39.setText(QtGui.QApplication.translate("MainWindow", "Opn", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_40.setText(QtGui.QApplication.translate("MainWindow", "Rel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("MainWindow", "Saved configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("MainWindow", "2016-04-18 07:49", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_41.setText(QtGui.QApplication.translate("MainWindow", "Ren", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_42.setText(QtGui.QApplication.translate("MainWindow", "De", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Left control area", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Reference Arm", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_19.setText(QtGui.QApplication.translate("MainWindow", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_20.setText(QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_6.setPrefix(QtGui.QApplication.translate("MainWindow", "Position: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "OCT Image Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Min. Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Max. Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Colormap", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(0, QtGui.QApplication.translate("MainWindow", "Gray", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(1, QtGui.QApplication.translate("MainWindow", "HSV", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(2, QtGui.QApplication.translate("MainWindow", "Jet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Dispersion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Coeff. B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Oceff. C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Polarization", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Half Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Quar. Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Scan line control", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_21.setText(QtGui.QApplication.translate("MainWindow", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_22.setText(QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_23.setText(QtGui.QApplication.translate("MainWindow", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_24.setText(QtGui.QApplication.translate("MainWindow", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_9.setPrefix(QtGui.QApplication.translate("MainWindow", "Length: ", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_10.setPrefix(QtGui.QApplication.translate("MainWindow", "Angle: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Visible Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Exposure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Hardware controls", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("MainWindow", "OCT Camera Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("MainWindow", "Int. Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("MainWindow", "Line Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("MainWindow", "Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("MainWindow", "Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("MainWindow", "Reference Arm", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_30.setText(QtGui.QApplication.translate("MainWindow", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_31.setText(QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_30.setPrefix(QtGui.QApplication.translate("MainWindow", "Position: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("MainWindow", "Light source", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_32.setText(QtGui.QApplication.translate("MainWindow", "Off/On", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("MainWindow", "Power", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("MainWindow", "Visible Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setText(QtGui.QApplication.translate("MainWindow", "Exposure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Left control area", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("MainWindow", "Scan Pattern", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_43.setText(QtGui.QApplication.translate("MainWindow", "Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_44.setText(QtGui.QApplication.translate("MainWindow", "Spiral", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_45.setText(QtGui.QApplication.translate("MainWindow", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_46.setText(QtGui.QApplication.translate("MainWindow", "Rect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("MainWindow", "Motion Correction", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_47.setText(QtGui.QApplication.translate("MainWindow", "Avg", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_48.setText(QtGui.QApplication.translate("MainWindow", "Subtract", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("MainWindow", "Angiography algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_49.setText(QtGui.QApplication.translate("MainWindow", "Speckle", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_50.setText(QtGui.QApplication.translate("MainWindow", "Complex \n"
"Differntial \n"
"Variance", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_51.setText(QtGui.QApplication.translate("MainWindow", "Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("MainWindow", "Save configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Angio B-scan", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("MainWindow", "OCT Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("MainWindow", "Angio Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("MainWindow", "Angio Projection", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("MainWindow", "Intensity and Phase data", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("MainWindow", "Raw OCT data", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("MainWindow", "Visible Camera image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Hardware center area", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "oct  image area", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_15.setText(QtGui.QApplication.translate("MainWindow", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_16.setText(QtGui.QApplication.translate("MainWindow", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_17.setText(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_18.setText(QtGui.QApplication.translate("MainWindow", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("MainWindow", "Hardware control header", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_36.setText(QtGui.QApplication.translate("MainWindow", "Live", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_37.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_38.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Top center button area", None, QtGui.QApplication.UnicodeUTF8))

import oct_gallery_resources_rc
import wasatch_logo_resources_rc
import vis_gallery_resources_rc
import colormap_resources_rc
