# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'microangio/assets/right_control_area.ui'
#
# Created: Wed Apr 20 14:58:35 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(746, 931)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(100, -50, 200, 1011))
        self.frame.setMinimumSize(QtCore.QSize(200, 0))
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtGui.QFrame(self.frame)
        self.frame_6.setMinimumSize(QtCore.QSize(195, 150))
        self.frame_6.setMaximumSize(QtCore.QSize(195, 200))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_8 = QtGui.QLabel(self.frame_6)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_8.setObjectName("label_8")
        self.verticalScrollBar = QtGui.QScrollBar(self.frame_6)
        self.verticalScrollBar.setGeometry(QtCore.QRect(20, 40, 16, 91))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.pushButton_8 = QtGui.QPushButton(self.frame_6)
        self.pushButton_8.setGeometry(QtCore.QRect(50, 40, 41, 27))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtGui.QPushButton(self.frame_6)
        self.pushButton_9.setGeometry(QtCore.QRect(50, 110, 41, 27))
        self.pushButton_9.setObjectName("pushButton_9")
        self.spinBox_6 = QtGui.QSpinBox(self.frame_6)
        self.spinBox_6.setGeometry(QtCore.QRect(50, 70, 91, 31))
        self.spinBox_6.setSuffix("")
        self.spinBox_6.setMaximum(10000)
        self.spinBox_6.setObjectName("spinBox_6")
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_7 = QtGui.QFrame(self.frame)
        self.frame_7.setMinimumSize(QtCore.QSize(195, 100))
        self.frame_7.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_9 = QtGui.QLabel(self.frame_7)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_9.setObjectName("label_9")
        self.spinBox_7 = QtGui.QSpinBox(self.frame_7)
        self.spinBox_7.setGeometry(QtCore.QRect(150, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_7.setFont(font)
        self.spinBox_7.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_7.setObjectName("spinBox_7")
        self.label_10 = QtGui.QLabel(self.frame_7)
        self.label_10.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalSlider_2 = QtGui.QSlider(self.frame_7)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtGui.QSlider(self.frame_7)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_3.setSliderPosition(77)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setInvertedAppearance(False)
        self.horizontalSlider_3.setInvertedControls(False)
        self.horizontalSlider_3.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_11 = QtGui.QLabel(self.frame_7)
        self.label_11.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.spinBox_8 = QtGui.QSpinBox(self.frame_7)
        self.spinBox_8.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_8.setFont(font)
        self.spinBox_8.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_8.setProperty("value", 99)
        self.spinBox_8.setObjectName("spinBox_8")
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_8 = QtGui.QFrame(self.frame)
        self.frame_8.setMinimumSize(QtCore.QSize(195, 70))
        self.frame_8.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_12 = QtGui.QLabel(self.frame_8)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_12.setObjectName("label_12")
        self.comboBox_3 = QtGui.QComboBox(self.frame_8)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 30, 71, 27))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.labelSnapshotThumbnail_5 = QtGui.QLabel(self.frame_8)
        self.labelSnapshotThumbnail_5.setGeometry(QtCore.QRect(90, 30, 24, 24))
        self.labelSnapshotThumbnail_5.setText("")
        self.labelSnapshotThumbnail_5.setPixmap(QtGui.QPixmap(":/thumbnails/images/colormaps/gray.jpg"))
        self.labelSnapshotThumbnail_5.setScaledContents(True)
        self.labelSnapshotThumbnail_5.setObjectName("labelSnapshotThumbnail_5")
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_9 = QtGui.QFrame(self.frame)
        self.frame_9.setMinimumSize(QtCore.QSize(195, 100))
        self.frame_9.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_14 = QtGui.QLabel(self.frame_9)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_14.setObjectName("label_14")
        self.spinBox_11 = QtGui.QSpinBox(self.frame_9)
        self.spinBox_11.setGeometry(QtCore.QRect(150, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_11.setFont(font)
        self.spinBox_11.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_11.setObjectName("spinBox_11")
        self.label_15 = QtGui.QLabel(self.frame_9)
        self.label_15.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalSlider_4 = QtGui.QSlider(self.frame_9)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalSlider_5 = QtGui.QSlider(self.frame_9)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_5.setSliderPosition(77)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setInvertedAppearance(False)
        self.horizontalSlider_5.setInvertedControls(False)
        self.horizontalSlider_5.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.label_16 = QtGui.QLabel(self.frame_9)
        self.label_16.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.spinBox_12 = QtGui.QSpinBox(self.frame_9)
        self.spinBox_12.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_12.setFont(font)
        self.spinBox_12.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_12.setProperty("value", 99)
        self.spinBox_12.setObjectName("spinBox_12")
        self.verticalLayout.addWidget(self.frame_9)
        self.frame_10 = QtGui.QFrame(self.frame)
        self.frame_10.setMinimumSize(QtCore.QSize(195, 100))
        self.frame_10.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_17 = QtGui.QLabel(self.frame_10)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_17.setObjectName("label_17")
        self.spinBox_13 = QtGui.QSpinBox(self.frame_10)
        self.spinBox_13.setGeometry(QtCore.QRect(150, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_13.setFont(font)
        self.spinBox_13.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_13.setObjectName("spinBox_13")
        self.label_18 = QtGui.QLabel(self.frame_10)
        self.label_18.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalSlider_6 = QtGui.QSlider(self.frame_10)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.horizontalSlider_7 = QtGui.QSlider(self.frame_10)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_7.setSliderPosition(77)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setInvertedAppearance(False)
        self.horizontalSlider_7.setInvertedControls(False)
        self.horizontalSlider_7.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.label_19 = QtGui.QLabel(self.frame_10)
        self.label_19.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.spinBox_14 = QtGui.QSpinBox(self.frame_10)
        self.spinBox_14.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_14.setFont(font)
        self.spinBox_14.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_14.setProperty("value", 99)
        self.spinBox_14.setObjectName("spinBox_14")
        self.verticalLayout.addWidget(self.frame_10)
        spacerItem = QtGui.QSpacerItem(20, 68, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_5 = QtGui.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(195, 150))
        self.frame_5.setMaximumSize(QtCore.QSize(195, 150))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_13 = QtGui.QLabel(self.frame_5)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_13.setObjectName("label_13")
        self.pushButton_19 = QtGui.QPushButton(self.frame_5)
        self.pushButton_19.setGeometry(QtCore.QRect(80, 40, 41, 27))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtGui.QPushButton(self.frame_5)
        self.pushButton_20.setGeometry(QtCore.QRect(80, 80, 41, 27))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtGui.QPushButton(self.frame_5)
        self.pushButton_21.setGeometry(QtCore.QRect(130, 60, 41, 27))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtGui.QPushButton(self.frame_5)
        self.pushButton_22.setGeometry(QtCore.QRect(30, 60, 41, 27))
        self.pushButton_22.setObjectName("pushButton_22")
        self.spinBox_9 = QtGui.QSpinBox(self.frame_5)
        self.spinBox_9.setGeometry(QtCore.QRect(10, 120, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_9.setFont(font)
        self.spinBox_9.setSuffix("")
        self.spinBox_9.setMaximum(9999)
        self.spinBox_9.setProperty("value", 5555)
        self.spinBox_9.setObjectName("spinBox_9")
        self.spinBox_10 = QtGui.QSpinBox(self.frame_5)
        self.spinBox_10.setGeometry(QtCore.QRect(110, 120, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_10.setFont(font)
        self.spinBox_10.setSuffix("")
        self.spinBox_10.setMaximum(360)
        self.spinBox_10.setProperty("value", 300)
        self.spinBox_10.setObjectName("spinBox_10")
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(195, 200))
        self.frame_3.setMaximumSize(QtCore.QSize(195, 200))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_4.setObjectName("label_4")
        self.labelSnapshotThumbnail_4 = QtGui.QLabel(self.frame_3)
        self.labelSnapshotThumbnail_4.setGeometry(QtCore.QRect(10, 30, 171, 141))
        self.labelSnapshotThumbnail_4.setText("")
        self.labelSnapshotThumbnail_4.setPixmap(QtGui.QPixmap(":/samples/images/vis_gallery/example_vis_camera_13.jpg"))
        self.labelSnapshotThumbnail_4.setScaledContents(True)
        self.labelSnapshotThumbnail_4.setObjectName("labelSnapshotThumbnail_4")
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(13, 180, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.spinBox_5 = QtGui.QSpinBox(self.frame_3)
        self.spinBox_5.setGeometry(QtCore.QRect(150, 180, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_5.setFont(font)
        self.spinBox_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalSlider = QtGui.QSlider(self.frame_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(70, 180, 71, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtGui.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(330, 30, 200, 800))
        self.frame_2.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_12 = QtGui.QFrame(self.frame_2)
        self.frame_12.setMinimumSize(QtCore.QSize(195, 200))
        self.frame_12.setMaximumSize(QtCore.QSize(195, 200))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_21 = QtGui.QLabel(self.frame_12)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_21.setObjectName("label_21")
        self.spinBox_16 = QtGui.QSpinBox(self.frame_12)
        self.spinBox_16.setGeometry(QtCore.QRect(150, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_16.setFont(font)
        self.spinBox_16.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_16.setProperty("value", 50)
        self.spinBox_16.setObjectName("spinBox_16")
        self.label_22 = QtGui.QLabel(self.frame_12)
        self.label_22.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalSlider_8 = QtGui.QSlider(self.frame_12)
        self.horizontalSlider_8.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.horizontalSlider_8.setProperty("value", 50)
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName("horizontalSlider_8")
        self.horizontalSlider_9 = QtGui.QSlider(self.frame_12)
        self.horizontalSlider_9.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_9.setSliderPosition(77)
        self.horizontalSlider_9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_9.setInvertedAppearance(False)
        self.horizontalSlider_9.setInvertedControls(False)
        self.horizontalSlider_9.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_9.setObjectName("horizontalSlider_9")
        self.label_23 = QtGui.QLabel(self.frame_12)
        self.label_23.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.spinBox_17 = QtGui.QSpinBox(self.frame_12)
        self.spinBox_17.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_17.setFont(font)
        self.spinBox_17.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_17.setMaximum(100)
        self.spinBox_17.setProperty("value", 100)
        self.spinBox_17.setObjectName("spinBox_17")
        self.spinBox_25 = QtGui.QSpinBox(self.frame_12)
        self.spinBox_25.setGeometry(QtCore.QRect(150, 100, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_25.setFont(font)
        self.spinBox_25.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_25.setMaximum(100)
        self.spinBox_25.setProperty("value", 100)
        self.spinBox_25.setObjectName("spinBox_25")
        self.horizontalSlider_15 = QtGui.QSlider(self.frame_12)
        self.horizontalSlider_15.setGeometry(QtCore.QRect(70, 100, 71, 16))
        self.horizontalSlider_15.setSliderPosition(77)
        self.horizontalSlider_15.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_15.setInvertedAppearance(False)
        self.horizontalSlider_15.setInvertedControls(False)
        self.horizontalSlider_15.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_15.setObjectName("horizontalSlider_15")
        self.label_33 = QtGui.QLabel(self.frame_12)
        self.label_33.setGeometry(QtCore.QRect(10, 100, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.spinBox_32 = QtGui.QSpinBox(self.frame_12)
        self.spinBox_32.setGeometry(QtCore.QRect(150, 130, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_32.setFont(font)
        self.spinBox_32.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_32.setMaximum(100)
        self.spinBox_32.setProperty("value", 100)
        self.spinBox_32.setObjectName("spinBox_32")
        self.horizontalSlider_22 = QtGui.QSlider(self.frame_12)
        self.horizontalSlider_22.setGeometry(QtCore.QRect(70, 130, 71, 16))
        self.horizontalSlider_22.setSliderPosition(77)
        self.horizontalSlider_22.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_22.setInvertedAppearance(False)
        self.horizontalSlider_22.setInvertedControls(False)
        self.horizontalSlider_22.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_22.setObjectName("horizontalSlider_22")
        self.label_42 = QtGui.QLabel(self.frame_12)
        self.label_42.setGeometry(QtCore.QRect(10, 130, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_2.addWidget(self.frame_12)
        self.frame_11 = QtGui.QFrame(self.frame_2)
        self.frame_11.setMinimumSize(QtCore.QSize(195, 150))
        self.frame_11.setMaximumSize(QtCore.QSize(195, 200))
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_20 = QtGui.QLabel(self.frame_11)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_20.setObjectName("label_20")
        self.verticalScrollBar_2 = QtGui.QScrollBar(self.frame_11)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(20, 40, 16, 91))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.pushButton_10 = QtGui.QPushButton(self.frame_11)
        self.pushButton_10.setGeometry(QtCore.QRect(50, 40, 41, 27))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtGui.QPushButton(self.frame_11)
        self.pushButton_11.setGeometry(QtCore.QRect(50, 110, 41, 27))
        self.pushButton_11.setObjectName("pushButton_11")
        self.spinBox_15 = QtGui.QSpinBox(self.frame_11)
        self.spinBox_15.setGeometry(QtCore.QRect(50, 70, 91, 31))
        self.spinBox_15.setSuffix("")
        self.spinBox_15.setMaximum(10000)
        self.spinBox_15.setObjectName("spinBox_15")
        self.verticalLayout_2.addWidget(self.frame_11)
        self.frame_14 = QtGui.QFrame(self.frame_2)
        self.frame_14.setMinimumSize(QtCore.QSize(195, 100))
        self.frame_14.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_25 = QtGui.QLabel(self.frame_14)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_25.setObjectName("label_25")
        self.pushButton_12 = QtGui.QPushButton(self.frame_14)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 30, 51, 27))
        self.pushButton_12.setObjectName("pushButton_12")
        self.spinBox_33 = QtGui.QSpinBox(self.frame_14)
        self.spinBox_33.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_33.setFont(font)
        self.spinBox_33.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_33.setMaximum(100)
        self.spinBox_33.setProperty("value", 100)
        self.spinBox_33.setObjectName("spinBox_33")
        self.horizontalSlider_23 = QtGui.QSlider(self.frame_14)
        self.horizontalSlider_23.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_23.setSliderPosition(77)
        self.horizontalSlider_23.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_23.setInvertedAppearance(False)
        self.horizontalSlider_23.setInvertedControls(False)
        self.horizontalSlider_23.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_23.setObjectName("horizontalSlider_23")
        self.label_43 = QtGui.QLabel(self.frame_14)
        self.label_43.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_2.addWidget(self.frame_14)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.frame_4 = QtGui.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(195, 200))
        self.frame_4.setMaximumSize(QtCore.QSize(195, 200))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_5 = QtGui.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_5.setObjectName("label_5")
        self.labelSnapshotThumbnail_6 = QtGui.QLabel(self.frame_4)
        self.labelSnapshotThumbnail_6.setGeometry(QtCore.QRect(10, 30, 171, 141))
        self.labelSnapshotThumbnail_6.setText("")
        self.labelSnapshotThumbnail_6.setPixmap(QtGui.QPixmap(":/samples/images/vis_gallery/example_vis_camera_13.jpg"))
        self.labelSnapshotThumbnail_6.setScaledContents(True)
        self.labelSnapshotThumbnail_6.setObjectName("labelSnapshotThumbnail_6")
        self.label_24 = QtGui.QLabel(self.frame_4)
        self.label_24.setGeometry(QtCore.QRect(13, 180, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.spinBox_18 = QtGui.QSpinBox(self.frame_4)
        self.spinBox_18.setGeometry(QtCore.QRect(150, 180, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_18.setFont(font)
        self.spinBox_18.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_18.setObjectName("spinBox_18")
        self.horizontalSlider_10 = QtGui.QSlider(self.frame_4)
        self.horizontalSlider_10.setGeometry(QtCore.QRect(70, 180, 71, 16))
        self.horizontalSlider_10.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_10.setObjectName("horizontalSlider_10")
        self.verticalLayout_2.addWidget(self.frame_4)

        self.retranslateUi(Form)
        self.comboBox_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Reference Arm", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("Form", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("Form", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_6.setPrefix(QtGui.QApplication.translate("Form", "Position: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "OCT Image Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Min. Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Max. Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Colormap", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(0, QtGui.QApplication.translate("Form", "Gray", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(1, QtGui.QApplication.translate("Form", "HSV", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(2, QtGui.QApplication.translate("Form", "Jet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Dispersion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Coeff. B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Oceff. C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Polarization", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Half Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "Quar. Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "Scan line control", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_19.setText(QtGui.QApplication.translate("Form", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_20.setText(QtGui.QApplication.translate("Form", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_21.setText(QtGui.QApplication.translate("Form", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_22.setText(QtGui.QApplication.translate("Form", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_9.setPrefix(QtGui.QApplication.translate("Form", "Length: ", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_10.setPrefix(QtGui.QApplication.translate("Form", "Angle: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Visible Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Exposure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Form", "OCT Camera Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Form", "Int. Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Form", "Line Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Form", "Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("Form", "Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Form", "Reference Arm", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("Form", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("Form", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_15.setPrefix(QtGui.QApplication.translate("Form", "Position: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Form", "Light source", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("Form", "Off/On", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("Form", "Power", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Visible Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Form", "Exposure", None, QtGui.QApplication.UnicodeUTF8))

import oct_gallery_resources_rc
import oct_gallery_resources_rc
import vis_gallery_resources_rc
import colormap_resources_rc
