# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'microangio/assets/vis_camera_widget.ui'
#
# Created: Mon Apr 25 10:20:25 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(661, 647)
        self.frame_3 = QtGui.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(10, 20, 195, 200))
        self.frame_3.setMinimumSize(QtCore.QSize(195, 200))
        self.frame_3.setMaximumSize(QtCore.QSize(195, 200))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_4.setObjectName("label_4")
        self.labelSnapshotThumbnail_4 = QtGui.QLabel(self.frame_3)
        self.labelSnapshotThumbnail_4.setGeometry(QtCore.QRect(10, 30, 171, 141))
        self.labelSnapshotThumbnail_4.setText("")
        self.labelSnapshotThumbnail_4.setPixmap(QtGui.QPixmap(":/samples/images/vis_gallery/example_vis_camera_13.jpg"))
        self.labelSnapshotThumbnail_4.setScaledContents(True)
        self.labelSnapshotThumbnail_4.setObjectName("labelSnapshotThumbnail_4")
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(13, 180, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.spinBox_3 = QtGui.QSpinBox(self.frame_3)
        self.spinBox_3.setGeometry(QtCore.QRect(150, 180, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalSlider = QtGui.QSlider(self.frame_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(70, 180, 71, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.frame_4 = QtGui.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(10, 240, 195, 150))
        self.frame_4.setMinimumSize(QtCore.QSize(195, 150))
        self.frame_4.setMaximumSize(QtCore.QSize(195, 150))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_5 = QtGui.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtGui.QPushButton(self.frame_4)
        self.pushButton.setGeometry(QtCore.QRect(80, 40, 41, 27))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtGui.QPushButton(self.frame_4)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 80, 41, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtGui.QPushButton(self.frame_4)
        self.pushButton_5.setGeometry(QtCore.QRect(130, 60, 41, 27))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtGui.QPushButton(self.frame_4)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 60, 41, 27))
        self.pushButton_6.setObjectName("pushButton_6")
        self.spinBox = QtGui.QSpinBox(self.frame_4)
        self.spinBox.setGeometry(QtCore.QRect(10, 120, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox.setFont(font)
        self.spinBox.setSuffix("")
        self.spinBox.setMaximum(9999)
        self.spinBox.setProperty("value", 5555)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtGui.QSpinBox(self.frame_4)
        self.spinBox_2.setGeometry(QtCore.QRect(110, 120, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setSuffix("")
        self.spinBox_2.setMaximum(360)
        self.spinBox_2.setProperty("value", 300)
        self.spinBox_2.setObjectName("spinBox_2")
        self.frame_5 = QtGui.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(230, 20, 195, 150))
        self.frame_5.setMinimumSize(QtCore.QSize(195, 150))
        self.frame_5.setMaximumSize(QtCore.QSize(195, 200))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_8 = QtGui.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_8.setObjectName("label_8")
        self.verticalScrollBar = QtGui.QScrollBar(self.frame_5)
        self.verticalScrollBar.setGeometry(QtCore.QRect(20, 40, 16, 91))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.pushButton_7 = QtGui.QPushButton(self.frame_5)
        self.pushButton_7.setGeometry(QtCore.QRect(50, 40, 41, 27))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtGui.QPushButton(self.frame_5)
        self.pushButton_8.setGeometry(QtCore.QRect(50, 110, 41, 27))
        self.pushButton_8.setObjectName("pushButton_8")
        self.spinBox_4 = QtGui.QSpinBox(self.frame_5)
        self.spinBox_4.setGeometry(QtCore.QRect(50, 70, 91, 31))
        self.spinBox_4.setSuffix("")
        self.spinBox_4.setMaximum(10000)
        self.spinBox_4.setObjectName("spinBox_4")
        self.frame_6 = QtGui.QFrame(Form)
        self.frame_6.setGeometry(QtCore.QRect(230, 240, 195, 100))
        self.frame_6.setMinimumSize(QtCore.QSize(195, 100))
        self.frame_6.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_9 = QtGui.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_9.setObjectName("label_9")
        self.spinBox_5 = QtGui.QSpinBox(self.frame_6)
        self.spinBox_5.setGeometry(QtCore.QRect(150, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_5.setFont(font)
        self.spinBox_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_5.setObjectName("spinBox_5")
        self.label_10 = QtGui.QLabel(self.frame_6)
        self.label_10.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalSlider_2 = QtGui.QSlider(self.frame_6)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtGui.QSlider(self.frame_6)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_3.setSliderPosition(77)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setInvertedAppearance(False)
        self.horizontalSlider_3.setInvertedControls(False)
        self.horizontalSlider_3.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_11 = QtGui.QLabel(self.frame_6)
        self.label_11.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.spinBox_6 = QtGui.QSpinBox(self.frame_6)
        self.spinBox_6.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_6.setFont(font)
        self.spinBox_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_6.setProperty("value", 99)
        self.spinBox_6.setObjectName("spinBox_6")
        self.frame_7 = QtGui.QFrame(Form)
        self.frame_7.setGeometry(QtCore.QRect(230, 390, 195, 70))
        self.frame_7.setMinimumSize(QtCore.QSize(195, 70))
        self.frame_7.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_12 = QtGui.QLabel(self.frame_7)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_12.setObjectName("label_12")
        self.comboBox_3 = QtGui.QComboBox(self.frame_7)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 30, 71, 27))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.labelSnapshotThumbnail_5 = QtGui.QLabel(self.frame_7)
        self.labelSnapshotThumbnail_5.setGeometry(QtCore.QRect(90, 30, 24, 24))
        self.labelSnapshotThumbnail_5.setText("")
        self.labelSnapshotThumbnail_5.setPixmap(QtGui.QPixmap(":/thumbnails/images/colormaps/gray.jpg"))
        self.labelSnapshotThumbnail_5.setScaledContents(True)
        self.labelSnapshotThumbnail_5.setObjectName("labelSnapshotThumbnail_5")
        self.frame_8 = QtGui.QFrame(Form)
        self.frame_8.setGeometry(QtCore.QRect(440, 20, 195, 100))
        self.frame_8.setMinimumSize(QtCore.QSize(195, 100))
        self.frame_8.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_13 = QtGui.QLabel(self.frame_8)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_13.setObjectName("label_13")
        self.spinBox_7 = QtGui.QSpinBox(self.frame_8)
        self.spinBox_7.setGeometry(QtCore.QRect(150, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_7.setFont(font)
        self.spinBox_7.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_7.setObjectName("spinBox_7")
        self.label_14 = QtGui.QLabel(self.frame_8)
        self.label_14.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalSlider_4 = QtGui.QSlider(self.frame_8)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalSlider_5 = QtGui.QSlider(self.frame_8)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_5.setSliderPosition(77)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setInvertedAppearance(False)
        self.horizontalSlider_5.setInvertedControls(False)
        self.horizontalSlider_5.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.label_15 = QtGui.QLabel(self.frame_8)
        self.label_15.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.spinBox_8 = QtGui.QSpinBox(self.frame_8)
        self.spinBox_8.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_8.setFont(font)
        self.spinBox_8.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_8.setProperty("value", 99)
        self.spinBox_8.setObjectName("spinBox_8")
        self.frame_9 = QtGui.QFrame(Form)
        self.frame_9.setGeometry(QtCore.QRect(440, 140, 195, 100))
        self.frame_9.setMinimumSize(QtCore.QSize(195, 100))
        self.frame_9.setMaximumSize(QtCore.QSize(195, 100))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_16 = QtGui.QLabel(self.frame_9)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label_16.setObjectName("label_16")
        self.spinBox_9 = QtGui.QSpinBox(self.frame_9)
        self.spinBox_9.setGeometry(QtCore.QRect(150, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_9.setFont(font)
        self.spinBox_9.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_9.setObjectName("spinBox_9")
        self.label_17 = QtGui.QLabel(self.frame_9)
        self.label_17.setGeometry(QtCore.QRect(10, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalSlider_6 = QtGui.QSlider(self.frame_9)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.horizontalSlider_7 = QtGui.QSlider(self.frame_9)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.horizontalSlider_7.setSliderPosition(77)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setInvertedAppearance(False)
        self.horizontalSlider_7.setInvertedControls(False)
        self.horizontalSlider_7.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.label_18 = QtGui.QLabel(self.frame_9)
        self.label_18.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.spinBox_10 = QtGui.QSpinBox(self.frame_9)
        self.spinBox_10.setGeometry(QtCore.QRect(150, 70, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spinBox_10.setFont(font)
        self.spinBox_10.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_10.setProperty("value", 99)
        self.spinBox_10.setObjectName("spinBox_10")

        self.retranslateUi(Form)
        self.comboBox_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Visible Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Exposure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Scan line control", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Form", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Form", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("Form", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("Form", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox.setPrefix(QtGui.QApplication.translate("Form", "Length: ", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_2.setPrefix(QtGui.QApplication.translate("Form", "Angle: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Reference Arm", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("Form", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("Form", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_4.setPrefix(QtGui.QApplication.translate("Form", "Position: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "OCT Image Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Min. Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Max. Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Colormap", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(0, QtGui.QApplication.translate("Form", "Gray", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(1, QtGui.QApplication.translate("Form", "HSV", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(2, QtGui.QApplication.translate("Form", "Jet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "Dispersion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Coeff. B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Oceff. C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Polarization", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Half Wave", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Quar. Wave", None, QtGui.QApplication.UnicodeUTF8))

import oct_gallery_resources_rc
import colormap_resources_rc
import vis_gallery_resources_rc
